# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26fa85f9093581db872a6499e5e5c51ca418e137a92b0d257768b777ef69ce63eea65b37c6e904f3640c6c745fa8275ff12b63003d57b767072d38699d9d560f

test:
  secret_key_base: d23788ea0efd59108a8854264bbea7f9acbd74fc9449cc4ebfb2cb854f64580ab88de91af25d5f1b46ef3648e98b7913283a68a177f853be9a0f910e399c3eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
